# SETTINGS CONSTANTS FOR PROGRAM

# LIMIT OF NUMBER OF POSSIBLE DECIMAL PLAES TO INPUT
# SETTING TO HIGH VALUES AT YOUR OWN RISK!
MAX_DECIMAL = 8

# PATH TO DIRECTORY FOR STORING PORTFOLIOS
DATA_PATH = "data/portfolios"
